# Generated by Django 4.0.4 on 2022-05-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '글', 'verbose_name_plural': '글'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
